name: hello-spark

containers:
 - dockerfile: Dockerfile
   rebuild:
     # Where our code lives inside the container.
     root: /code
     # The command used to rebuild our code inside the container.
     command: ./gradlew package
     # A list of input sources that get synced into the container prior to builds.
     sources:
       - build.gradle
       - settings.gradle
       - src

profiles:
  stable:
    max_memory: 0.5G
    max_cpu: 0.5
  canary:
    max_memory: 0.5G
    max_cpu: 0.5G
    weight: 10.0 # percentage of traffic to route to this class of deployment
  default:
    max_memory: 0.25G
    max_cpu: 0.25

branches:
  master: stable
  canary: canary
  dev/*: default
