---
apiVersion: v1
kind: Service
metadata:
  name: blackbird
spec:
  selector:
    app: blackbird
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: blackbird}
spec:
  replicas: 1
  selector:
    matchLabels: {app: blackbird}
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      name: blackbird
      labels: {app: blackbird}
    spec:
      volumes:
      - name: docker-sock
        hostPath: {path: /var/run/docker.sock}
      - name: docker-directory
        hostPath: {path: /var/lib/docker}
      - name: skunkworks-config
        secret: {secretName: skunkworks-config}
      containers:
      - image: __IMAGE__
        imagePullPolicy: IfNotPresent
        name: blackbird
        env:
        - {name: DOCKER_API_VERSION, value: '1.12'}
        - {name: SKUNKWORKS_CONFIG, value: /etc/skunkworks/skunkworks.yaml}
        resources:
          limits:
            memory: 1G
            cpu: 0.25
        securityContext: {privileged: true}
        volumeMounts:
        - {mountPath: /var/run/docker.sock, name: docker-sock, readOnly: false}
        - {mountPath: /var/lib/docker, name: docker-directory, readOnly: false}
        - {mountPath: /etc/skunkworks, name: skunkworks-config, readOnly: true}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
