apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: blackbird}
spec:
  replicas: 1
  selector:
    matchLabels: {app: blackbird}
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels: {app: blackbird}
      name: blackbird
    spec:
      volumes:
      - name: docker-sock
        hostPath: {path: /var/run/docker.sock}
      - name: docker-directory
        hostPath: {path: /var/lib/docker}
      - name: docker-password
        secret: {secretName: docker-password}
      containers:
      - image: gcr.io/datawire-sandbox/blackbird:v25
        imagePullPolicy: IfNotPresent
        name: blackbird
        env:
        - {name: DOCKER_API_VERSION, value: '1.12'}
        resources: {}
        securityContext: {privileged: true}
        volumeMounts:
        - {mountPath: /var/run/docker.sock, name: docker-sock, readOnly: false}
        - {mountPath: /var/lib/docker, name: docker-directory, readOnly: false}
        - {mountPath: /etc/secrets, name: docker-password, readOnly: true}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
