gems:
  - jekyll-redirect-from

title: Forge
email: hello@datawire.io
author: "Datawire.io"
description: "Forge: Fast build system for Kubernetes services"
keywords: "Forge, Kubernetes, microservices"

baseurl: ""
url: "http://forge.sh" # the base hostname & protocol for your site
twitter_username: datawireio
github_username:  datawire

# use this to define the categories of your documentation
category-list:
  - "tutorials"
  - "discussion"
  - "reference"

# optionally you can define icon for each category (for the sidebar)
# Doc42 uses Font Awesome
category-icons: [code, question-circle, code, expand]

# Build settings
markdown: kramdown
